In [3]:
import numpy as np
from keras.utils import np_utils
import tensorflow as tf
# tf.python.control_flow_ops = tf

In [32]:
np.random.seed(42)
X = np.array([[0,0],[0,1],[1,0],[1,1]]).astype('float32')
y = np.array([[0],[1],[0],[0]]).astype('float32')
y

array([[0.],
       [1.],
       [0.],
       [0.]], dtype=float32)

In [33]:
from keras.models import Sequential
from keras.layers.core import Dense,Activation,Flatten
# One-hot encoding the output
y = np_utils.to_categorical(y)
y

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [29]:
# Building the model
xor = Sequential()
xor.add(Dense(32, input_dim=2))
xor.add(Activation("tanh"))
xor.add(Dense(2))
xor.add(Activation("sigmoid"))

xor.compile(loss="categorical_crossentropy", optimizer="adam", metrics = ['accuracy'])

# Uncomment this line to print the model architecture
xor.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 32)                96        
_________________________________________________________________
activation_15 (Activation)   (None, 32)                0         
_________________________________________________________________
dense_16 (Dense)             (None, 2)                 66        
_________________________________________________________________
activation_16 (Activation)   (None, 2)                 0         
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [34]:
# Fitting the model
history = xor.fit(X, y, nb_epoch=1000, verbose=0)

# Scoring the model
score = xor.evaluate(X, y)
print("\nAccuracy: ", score[-1])

# Checking the predictions
print("\nPredictions:")
print(xor.predict_proba(X))

/Users/randall/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


4/4 [==============================] - 0s 6ms/step

Accuracy:  1.0

Predictions:
[[7.6598543e-01 4.6652160e-03]
 [2.7413496e-03 3.5783106e-01]
 [9.8989654e-01 2.9393161e-05]
 [2.4125350e-01 1.2014072e-03]]
